services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: personal-finance-app-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: personal-finance-app-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
